username: xunfei
password: xunfei
host: localhost
video_receiver_port: 54321
video_server_port: 54322
audio_receiver_port: 54323
audio_server_port: 54324
is_transcribe: false
fps: 10
quality: 10
label: 1
